### ISSUE TITLE
图片搜索性能优化

### ISSUE THREAD

**Issue by yylstudy** [AndsGo/reverse_image_search#3]
fastapi方法上都是async，这个会导致接口是单线程同步，去除后，发现
image_embedding.timm(model_name='resnet50')这个方法也是同步的，请问下有什么办法能解决吗，谢谢！

**Comment by AndsGo** [comment]
我这边测试时发现这个image_embedding.timm(model_name='resnet50') 是普通的def方法，支持多线程跑。
你是用测试并发是多少呢。有监控cpu使用率吗，image_embedding.timm(model_name='resnet50')这个cpu消耗很大，跑慢后程序可能会阻塞。
